### ISSUE TITLE
规则不可编辑阿

### ISSUE THREAD

**Issue by syuhaitao** [bigbigbo/rule-editor#1]

**Comment by tangxiaobin17** [comment]
修改src/example/App.js文件中disable为false，就可以编辑了

**Comment by syuhaitao** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yuzd** [comment]
改成false
还是不可以编辑，js运行有报错

![image](https://user-images.githubusercontent.com/16083659/221389545-4776ceaf-93dd-434c-8c95-da27304bc847.png)

**Comment by syuhaitao** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by syuhaitao** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
